name: DeployApp
on: 
  workflow_dispatch:
    inputs:
      target:
        description: 'Environment to deploy to'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - test
          - prod

jobs:
  jobDeploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./src/InfrastructureAsCode/main.bicep
          parameters: environment=${{ env.targetEnv }}
          scope: resource-group