name: ManualWorkflow
on: 
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Step1
        run: echo Step1 complete!
      - name: Step2
        run: echo Step2 complete!

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'Ready for prod–ship it!'
          color: 'magenta'